"""Initial schema: PostGIS, parcels, layer_features, reports, payments.

Hand-written rather than autogenerated: the PostGIS extension has to exist before any
geometry column, and autogenerate would never emit that.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-09
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SRID = 25830


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # btree_gist lets a GiST index mix a scalar column with a geometry one; without it
    # the (layer_code, geom) index below fails: varchar has no default GiST opclass.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table(
        "parcels",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("refcat", sa.String(length=20), nullable=False),
        sa.Column("municipality", sa.String(length=120), nullable=False, server_default=""),
        sa.Column("province", sa.String(length=120), nullable=False, server_default=""),
        sa.Column("use", sa.String(length=120), nullable=False, server_default=""),
        sa.Column("cadastral_area_m2", sa.Float(), nullable=False, server_default="0"),
        sa.Column("built_area_m2", sa.Float(), nullable=False, server_default="0"),
        sa.Column("measured_area_m2", sa.Float(), nullable=False, server_default="0"),
        sa.Column(
            "subplots",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("lat", sa.Float(), nullable=False, server_default="0"),
        sa.Column("lon", sa.Float(), nullable=False, server_default="0"),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON", srid=SRID, spatial_index=False
            ),
            nullable=True,
        ),
        sa.Column("refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_parcels_refcat", "parcels", ["refcat"], unique=True)
    op.create_index("ix_parcels_geom", "parcels", ["geom"], postgresql_using="gist")

    op.create_table(
        "layer_features",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("layer_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON", srid=SRID, spatial_index=False
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_layer_features_layer_code", "layer_features", ["layer_code"])
    op.create_index("ix_layer_features_geom", "layer_features", ["geom"], postgresql_using="gist")
    op.create_index(
        "ix_layer_features_code_geom",
        "layer_features",
        ["layer_code", "geom"],
        postgresql_using="gist",
    )

    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("refcat", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("parcel_id", sa.Integer(), sa.ForeignKey("parcels.id"), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column(
            "payload",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("pdf_path", sa.String(length=512), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_reports_token", "reports", ["token"], unique=True)
    op.create_index("ix_reports_refcat", "reports", ["refcat"])
    op.create_index("ix_reports_status", "reports", ["status"])

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("stripe_event_id", sa.String(length=120), nullable=False),
        sa.Column("stripe_session_id", sa.String(length=120), nullable=True),
        sa.Column("stripe_payment_intent", sa.String(length=120), nullable=True),
        sa.Column("refcat", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("currency", sa.String(length=8), nullable=False, server_default="eur"),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="paid"),
        sa.Column("report_id", sa.Integer(), sa.ForeignKey("reports.id"), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "raw_event",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    # Unique on the event id is what makes webhook delivery idempotent: a Stripe retry
    # hits this constraint instead of charging the pipeline twice.
    op.create_index("ix_payments_stripe_event_id", "payments", ["stripe_event_id"], unique=True)
    op.create_index("ix_payments_stripe_session_id", "payments", ["stripe_session_id"])
    op.create_index("ix_payments_status", "payments", ["status"])
    op.create_index("ix_payments_refcat", "payments", ["refcat"])


def downgrade() -> None:
    op.drop_table("payments")
    op.drop_table("reports")
    op.drop_index("ix_layer_features_code_geom", table_name="layer_features")
    op.drop_index("ix_layer_features_geom", table_name="layer_features")
    op.drop_table("layer_features")
    op.drop_index("ix_parcels_geom", table_name="parcels")
    op.drop_table("parcels")
    # PostGIS itself is left in place: other schemas in the same database may use it.
